name: docs

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme sphinx_rtd_dark_mode myst_nb
          pip install scipy<=0.11.0 pennylane==0.33.1 pennylane-lightning==0.33.1
          pip install sympy qiskit-terra qiskit-aer matplotlib pylatexenc cirq qutip qutip_qip
          python setup.py install
      - name: Sphinx build
        run: |
          sphinx-build docs/source _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true